### ISSUE TITLE
cards sides are wrong

### ISSUE THREAD

**Issue by AriaMoradi** [damaru2/ankigenbot#1]
I generated a card and the word is on the back and the definition is on the front

**Comment by damaru2** [comment]
That is the way it is supposed to be. It is better for your learning, since the aim is that when you are speaking a language and you are thinking about a concept you are able to find the right word to use. And that is the whole point of the sentence example. Also, since that way is harder, the other direction usually comes for free, from my experience. It is also the standard format of Supermemo, the original app the started with the spaced repetition algorithms.

That said, I can add a command to choose to receive them in the other order although I think in that case the sentence example does not make any sense (if it is in the front it is way easier to get the meaning from the context not really making you learn the word and if it is in the back is not that useful)

**Comment by AriaMoradi** [comment]
Usually the example is used to know how to use the word.

**Comment by AriaMoradi** [comment]
anyways, I'm going to make an option for the card to be flipped or not,
and use https://www.oxfordlearnersdictionaries.com/ as the dictionary(English to English only)
in my fork of the project.
you can merge the commits later.

**Comment by damaru2** [comment]
I'm almost done adding the feature to swap the front and back. Having also the oxford dictionary would be awesome, thanks

**Comment by damaru2** [comment]
It's online now. The new command is swap, as can be seen in the command autocompletion

**Comment by damaru2** [comment]
I'll close this issue now, if you add support for the oxford dictionary open a new issue or submit a pull request and I'll be happy to take a loot at it.
