### ISSUE TITLE
more words

### ISSUE THREAD

**Issue by isotestardo** [damaru2/ankigenbot#7]
Hey David,
I'm not sure if this is the right place to write. I was wondering if it would be possible to implement searching for phrase and idioms ( ' bite a bullet' e.g.).

Do you also think it could be possible to split definition and example in two separate fields? That will give the possibility to customize the cards on Anki

**Comment by damaru2** [comment]
The problem with the idioms is that there is not a source with a manageable API from where to take them.

Split definition and example would not be impossible but it'd be rather complex since users by default wouldn't have a template according to that and the bot would need to create it, and tweaking user's templates is not something I think I want the bot to do. 

The examples have always a very regular format, they start with "(e.g." and end with ")" so if at the end of the day you want that for customization your can add an extra step extracting the example, with a simple regex with any text editor

**Comment by isotestardo** [comment]
I was thinking of Oxford dictionary, does not it provide idioms and manageable API?

You are right about split definition and example.
Anyway , thank you for your great work!

**Comment by damaru2** [comment]
> I was thinking of Oxford dictionary, does not it provide idioms and manageable API?

Not for free

**Comment by damaru2** [comment]
Closing this issue since queries were solved
